### ISSUE TITLE
What's the point of CMD ["/usr/bin/phantomjs"]?

### ISSUE THREAD

**Issue by vitr** [fatihcode/dockerhub#6]
`docker run cmfatih/phantomjs /usr/bin/phantomjs -v`
It will run anyway with or without this CMD, but if I have CMD I'll have  one phantomjs process in the background and another one for the docker run. Please, correct me if I misunderstand something here.

**Comment by fatihcode** [comment]
`CMD` directive ( https://github.com/fatihcode/dockerhub/blob/master/phantomjs/Dockerfile#L34 ) in Dockerfile is an optional command. So if you just run the container without a command then it will prompt to `phantomjs` REPL

```
docker run -it cmfatih/phantomjs
phantomjs> 
```

On the other hand; the following command overrides `CMD` directive.
```
docker run cmfatih/phantomjs /usr/bin/phantomjs -v
1.9.7
```

Also;

> but if I have CMD I'll have one phantomjs process in the background and another one for the docker run. Please, correct me if I misunderstand something here.

No since `/usr/bin/phantomjs -v` override the `CMD` directive. You will have only one process.

You can find more information about `CMD` command at https://docs.docker.com/engine/reference/run/#cmd-default-command-or-options

**Comment by vitr** [comment]
got it, thank you!
